llm:
  provider: huggingface
  config:
    model: 'mistralai/Mixtral-8x7B-Instruct-v0.1'
    temperature: 0.5
    max_tokens: 250
    top_p: 1
    stream: true

embedder:
  provider: huggingface
  config:
    model: 'sentence-transformers/all-mpnet-base-v2'
